# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vbguest.auto_update = false
  config.ssh.insert_key = false
  
  
  config.vm.define "server" do |s|
    s.vm.box = "debian/bookworm64"
    s.vm.network "private_network", ip: "192.168.56.10"
    s.vm.network "private_network", ip: "192.168.57.10", virtualbox__intnet: true 
    s.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y isc-dhcp-server
        cp /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.bak
        cp /vagrant/shared/dhcp_settings/interfaces.config  /etc/default/isc-dhcp-server
        cp /vagrant/shared/dhcp_settings/dhcpd.config  /etc/dhcp/dhcpd.conf
        systemctl restart isc-dhcp-server
      SHELL
  end #Server


  config.vm.define "client2" do |c1|
    c1.vm.box = "debian/bookworm64"
    c1.vm.network "private_network", mac: "5CA1AB1E0001", auto_config: false, virtualbox__intnet: true 
    c1.vm.provision "shell", inline: "dhclient eth1"
  end #Client1

  config.vm.define "client1" do |c2|
    c2.vm.box = "debian/bookworm64"
    c2.vm.network "private_network", mac: "5CA1AB1E0002", auto_config: false, virtualbox__intnet: true
    c2.vm.provision "shell", inline: "dhclient eth1"
  end #Client2

end
