# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vbguest.auto_update = false

  config.vm.box = "debian/bookworm64"
  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end #web
end
