# -*- mode: ruby -*-
# vi: set ft=ruby :

webservers = ["w1", 8080,4433, "w2", 8081,4434]

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.ssh.insert_key = false

  config.vm.box = "debian/bookworm64"

  webservers.each_slice(3) do |servername, port, ssl_port|
    config.vm.define servername do |web|
      web.vm.hostname = servername
      web.vm.network "forwarded_port", guest: 80, host: port
      web.vm.network "forwarded_port", guest: 80, host: ssl_port
    end # web
  end # webserver
end
