# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vbguest.auto_update = false
  config.ssh.insert_key = false

  config.vm.box = "debian/bookworm64"
  config.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get upgrade -y
      apt-get install -y bind9 bind9utils bind9-doc
      cp -v /vagrant/named /etc/default/
    SHELL

  config.vm.define "master" do |m|
    m.vm.network "private_network", ip: "192.168.57.103"
    m.vm.provision "shell", inline: <<-SHELL
      cp -v /vagrant/named.conf.options /etc/bind/
      cp -v /vagrant/named.conf.local /etc/bind/
    SHELL
  end

  config.vm.define "slave" do |s|
    s.vm.network "private_network", ip: "192.168.57.102"
  end

end
