# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vbguest.auto_update = false
  config.ssh.insert_key = false

  config.vm.box = "debian/bookworm64"
  config.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get upgrade -y
      apt-get install -y bind9 bind9utils bind9-doc
      cp -v /vagrant/dns_conf/named /etc/default/
      cp -v /vagrant/dns_conf/named.conf.options /etc/bind/
    SHELL

  config.vm.define "master" do |m|
    m.vm.hostname = "tierra"
    m.vm.network "private_network", ip: "192.168.57.103"
    m.vm.provision "shell", inline: <<-SHELL
      cp -v /vagrant/dns_conf/master/named.conf.local /etc/bind/
      cp -v /vagrant/dns_conf/master/sistema.test.dns /var/lib/bind/
      cp -v /vagrant/dns_conf/master/sistema.test.rev /var/lib/bind/
      chown bind:bind /var/lib/bind/*
      systemctl restart named
    SHELL
  end

  config.vm.define "slave" do |s|
    s.vm.hostname = "venus"
    s.vm.network "private_network", ip: "192.168.57.102"
    s.vm.provision "shell", inline: <<-SHELL
      cp -v /vagrant/dns_conf/slave/named.conf.local /etc/bind/
      systemctl restart named
    SHELL
  end

end
