# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
    config.ssh.insert_key = false
    config.vm.box = "debian/bullseye64"
    config.vm.hostname = "app"
    config.vm.network "private_network", ip: "192.168.57.100"

end